// Schema-sync guard. Runs as part of `npm test`.
//
// Catches the #1 maintenance trap in this repo: tests/app.test.ts inlines a
// copy of the D1 schema as a string (the vitest worker runtime can't read
// migrations from disk). If a migration adds/changes a column and the inline
// copy is not updated, the tests keep passing but silently stop reflecting
// production.
//
// Both sides are committed fixtures generated by scripts/gen-schema.mjs from
// the real sources (migrations/*.sql and the `schemaSql` string in
// app.test.ts). This test compares the two fixtures — no node:fs in the
// worker. The authoritative live check is `node scripts/check-schema.mjs`
// (run in CI / pre-commit), which diffs the real sources and regenerates the
// fixtures, failing if the committed copies are stale.
import { describe, expect, it } from "vitest";
import { MIGRATION_COLUMNS } from "./migrations.schema";
import { INLINE_COLUMNS } from "./inline.schema";
import { diffSchemasFromRecords } from "./schemaParser";

describe("schema sync: inline test schema mirrors migrations", () => {
  it("per-table column sets match (migrations vs inline test schema)", () => {
    const diffs = diffSchemasFromRecords(MIGRATION_COLUMNS, INLINE_COLUMNS);
    if (diffs.length) {
      throw new Error(
        "Inline test schema is out of sync with migrations/. Regenerate the\n" +
          "fixtures with `node scripts/gen-schema.mjs` after updating the\n" +
          "`schemaSql` string in tests/app.test.ts (or a migration).\n\n" +
          diffs.map((d) => "  - " + d).join("\n")
      );
    }
    expect(Object.keys(MIGRATION_COLUMNS).length).toBeGreaterThan(0);
    expect(Object.keys(INLINE_COLUMNS).length).toBe(Object.keys(MIGRATION_COLUMNS).length);
  });
});
