#!/usr/bin/env node
// Authoritative schema-sync checker (no test runner required).
// Usage: node scripts/check-schema.mjs
// Exits non-zero if tests/app.test.ts inline schema diverges from migrations/.
//
// Does TWO things:
//   1) Live diff: parses migrations/*.sql (source of truth) vs the inline
//      `schemaSql` in tests/app.test.ts and fails on any column/table drift.
//   2) Fixture freshness: regenerates tests/*.schema.ts and fails if the
//      committed copies differ (i.e. a migration or inline change wasn't
//      followed by `node scripts/gen-schema.mjs`).
//
// Self-contained copy of the parser in tests/schemaParser.ts (Node can't import
// the .ts module directly). Keep the two in sync if you change parsing logic.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

function stripComments(sql) {
  return sql.replace(/--[^\n]*/g, " ").replace(/\/\*[\s\S]*?\*\//g, " ");
}
function splitTopLevel(body) {
  const out = []; let depth = 0, cur = "";
  for (const ch of body) {
    if (ch === "(") depth++; else if (ch === ")") depth = Math.max(0, depth - 1);
    if (ch === "," && depth === 0) { out.push(cur); cur = ""; } else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out;
}
function extractColumns(body) {
  const cols = new Set();
  const kw = new Set(["primary", "foreign", "unique", "check", "constraint", "key"]);
  for (const seg of splitTopLevel(body)) {
    const t = seg.trim(); if (!t) continue;
    const fw = t.split(/\s+/)[0].replace(/[`"]/g, "").toLowerCase();
    if (!fw || kw.has(fw) || !/^[a-z_][\w]*$/.test(fw)) continue;
    cols.add(fw);
  }
  return cols;
}
function parseSchema(sql) {
  const clean = stripComments(sql);
  const model = new Map();
  const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`"]?([A-Za-z_][\w]*)[`"]?\s*\(([\s\S]*?)\)\s*;/gi;
  let m;
  while ((m = createRe.exec(clean)) !== null) model.set(m[1].toLowerCase(), extractColumns(m[2]));
  const alterRe = /ALTER\s+TABLE\s+[`"]?([A-Za-z_][\w]*)[`"]?\s+ADD\s+COLUMN\s+[`"]?([A-Za-z_][\w]*)/gi;
  while ((m = alterRe.exec(clean)) !== null) {
    const name = m[1].toLowerCase();
    const e = model.get(name) ?? new Set(); e.add(m[2].toLowerCase()); model.set(name, e);
  }
  return model;
}
function toRecord(model) {
  const out = {};
  for (const [t, cols] of model) out[t] = [...cols].sort();
  return out;
}
function diffRecords(a, b) {
  const diffs = [];
  const tables = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const t of tables) {
    const ac = a[t], bc = b[t];
    if (!ac) { diffs.push(`Table "${t}" in inline schema but NOT in migrations.`); continue; }
    if (!bc) { diffs.push(`Table "${t}" in migrations but NOT in inline schema.`); continue; }
    const missing = ac.filter((c) => !bc.includes(c)).sort();
    const extra = bc.filter((c) => !ac.includes(c)).sort();
    if (missing.length) diffs.push(`Table "${t}": migrations has columns missing from inline: ${missing.join(", ")}.`);
    if (extra.length) diffs.push(`Table "${t}": inline has columns missing from migrations: ${extra.join(", ")}.`);
  }
  return diffs;
}
function fixtureContent(name, record) {
  return (
    `// AUTO-GENERATED by scripts/gen-schema.mjs. Do not edit by hand.\n` +
    `// Source of truth: migrations/*.sql + tests/app.test.ts schemaSql.\n` +
    `// Regenerate after any schema change.\n` +
    `export const ${name}: Record<string, string[]> = ` + JSON.stringify(record, null, 2) + ";\n"
  );
}

const dir = join(root, "migrations");
const migSql = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort().map((f) => readFileSync(join(dir, f), "utf8")).join("\n");
const migrationRec = toRecord(parseSchema(migSql));

const testSrc = readFileSync(join(root, "tests", "app.test.ts"), "utf8");
const sm = /const\s+schemaSql\s*=\s*`([\s\S]*?)`\s*;/.exec(testSrc);
if (!sm) throw new Error("Could not find inline `schemaSql` in tests/app.test.ts");
const inlineRec = toRecord(parseSchema(sm[1]));

let failed = false;

// 1) Live diff.
const diffs = diffRecords(migrationRec, inlineRec);
if (diffs.length) {
  failed = true;
  console.error("✗ Schema drift detected between migrations/ and inline test schema:");
  for (const d of diffs) console.error("  - " + d);
  console.error("\nFix: update the `schemaSql` string in tests/app.test.ts to match migrations/.");
}

// 2) Fixture freshness.
for (const [name, rec] of [["MIGRATION_COLUMNS", migrationRec], ["INLINE_COLUMNS", inlineRec]]) {
  const fileBase = name === "MIGRATION_COLUMNS" ? "migrations" : name === "INLINE_COLUMNS" ? "inline" : name.toLowerCase();
  const path = join(root, "tests", fileBase + ".schema.ts");
  const fresh = fixtureContent(name, rec);
  let current = "";
  try { current = readFileSync(path, "utf8"); } catch { /* missing */ }
  if (current !== fresh) {
    failed = true;
    console.error(`✗ Fixture ${name.toLowerCase()}.schema.ts is stale. Run: node scripts/gen-schema.mjs`);
  }
}

if (failed) process.exit(1);
console.log(`✓ Schema in sync (${Object.keys(migrationRec).length} tables mirrored) and fixtures current.`);
process.exit(0);
