#!/usr/bin/env node
// Generates tests/*.schema.ts fixtures so the in-worker schema-sync test can
// compare the migration-derived schema against the inline test schema WITHOUT
// touching node:fs (vitest-pool-workers does not implement fs in the worker
// runtime). Both fixtures are generated artifacts; the source of truth is
// migrations/*.sql (and the mirrored `schemaSql` in tests/app.test.ts).
//
//   node scripts/gen-schema.mjs    # write/update both fixtures
//
// `scripts/check-schema.mjs` runs the live migrations-vs-inline diff AND
// regenerates these fixtures, failing if the committed copies are stale.
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

function stripComments(sql) {
  return sql.replace(/--[^\n]*/g, " ").replace(/\/\*[\s\S]*?\*\//g, " ");
}
function splitTopLevel(body) {
  const out = []; let depth = 0, cur = "";
  for (const ch of body) {
    if (ch === "(") depth++; else if (ch === ")") depth = Math.max(0, depth - 1);
    if (ch === "," && depth === 0) { out.push(cur); cur = ""; } else cur += ch;
  }
  if (cur.trim()) out.push(cur);
  return out;
}
function extractColumns(body) {
  const cols = new Set();
  const kw = new Set(["primary", "foreign", "unique", "check", "constraint", "key"]);
  for (const seg of splitTopLevel(body)) {
    const t = seg.trim(); if (!t) continue;
    const fw = t.split(/\s+/)[0].replace(/[`"]/g, "").toLowerCase();
    if (!fw || kw.has(fw) || !/^[a-z_][\w]*$/.test(fw)) continue;
    cols.add(fw);
  }
  return cols;
}
function parseSchema(sql) {
  const clean = stripComments(sql);
  const model = new Map();
  const createRe = /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?[`"]?([A-Za-z_][\w]*)[`"]?\s*\(([\s\S]*?)\)\s*;/gi;
  let m;
  while ((m = createRe.exec(clean)) !== null) model.set(m[1].toLowerCase(), extractColumns(m[2]));
  const alterRe = /ALTER\s+TABLE\s+[`"]?([A-Za-z_][\w]*)[`"]?\s+ADD\s+COLUMN\s+[`"]?([A-Za-z_][\w]*)/gi;
  while ((m = alterRe.exec(clean)) !== null) {
    const name = m[1].toLowerCase();
    const e = model.get(name) ?? new Set(); e.add(m[2].toLowerCase()); model.set(name, e);
  }
  return model;
}

function emit(name, model) {
  const out = {};
  for (const [t, cols] of model) out[t] = [...cols].sort();
  const content =
    `// AUTO-GENERATED by scripts/gen-schema.mjs. Do not edit by hand.\n` +
    `// Source of truth: migrations/*.sql + tests/app.test.ts schemaSql.\n` +
    `// Regenerate after any schema change.\n` +
    `export const ${name}: Record<string, string[]> = ` + JSON.stringify(out, null, 2) + ";\n";
  // Filename maps the const name to the committed fixture:
  //   MIGRATION_COLUMNS -> migrations.schema.ts
  //   INLINE_COLUMNS    -> inline.schema.ts
  const fileBase =
    name === "MIGRATION_COLUMNS" ? "migrations" : name === "INLINE_COLUMNS" ? "inline" : name.toLowerCase();
  writeFileSync(join(root, "tests", fileBase + ".schema.ts"), content);
  return Object.keys(out).length;
}

// 1) Migration-derived model (source of truth).
const dir = join(root, "migrations");
const migSql = readdirSync(dir).filter((f) => f.endsWith(".sql")).sort().map((f) => readFileSync(join(dir, f), "utf8")).join("\n");
const nMig = emit("MIGRATION_COLUMNS", parseSchema(migSql));

// 2) Inline test schema (mirrored in tests/app.test.ts).
const testSrc = readFileSync(join(root, "tests", "app.test.ts"), "utf8");
const sm = /const\s+schemaSql\s*=\s*`([\s\S]*?)`\s*;/.exec(testSrc);
if (!sm) throw new Error("Could not find inline `schemaSql` in tests/app.test.ts");
const nInline = emit("INLINE_COLUMNS", parseSchema(sm[1]));

console.log(`✓ Wrote tests/migrations.schema.ts (${nMig} tables) and tests/inline.schema.ts (${nInline} tables).`);
