import type { Card } from './types';

// Preloaded starter cards based on Wild Jazmine Wellness themes.
// Designed so the board is useful on first open.
export function seedCards(): Card[] {
  const now = new Date().toISOString();
  const mk = (
    i: number,
    partial: Omit<
      Card,
      | 'id'
      | 'createdAt'
      | 'updatedAt'
      | 'draft'
      | 'checklist'
      | 'media'
      | 'resources'
      | 'customFields'
    >,
  ): Card => ({
    id: `seed-${i}`,
    createdAt: now,
    updatedAt: now,
    draft: '',
    checklist: [],
    media: [],
    resources: [],
    customFields: [],
    ...partial,
  });

  return [
    mk(1, {
      title: 'Finishing Foundations / starting in-person EFW training',
      description:
        'Announce the completion of Foundations training and the pivot to in-person EFT with horses (EFW). Personal milestone + soft launch of the next chapter.',
      category: 'Practicum / Training Milestones',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W28',
      tags: ['milestone', 'efw', 'announcement'],
      links: [],
      notes: 'Tie to the "why horses" narrative. Keep it warm, not braggy.',
      contentPillar: 'Behind the work',
      platformReady: false,
    }),
    mk(2, {
      title: 'EFT / EFCT certificate announcement',
      description:
        'Share the newly earned EFT / EFCT certification. Short celebratory post + what it means for clients.',
      category: 'Professional Education',
      platforms: ['Instagram', 'LinkedIn'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['certification', 'eft', 'credibility'],
      links: [],
      notes: '',
      contentPillar: 'Credentials',
      platformReady: false,
    }),
    mk(3, {
      title: 'What is EFT / EFCT?',
      description:
        'Educational explainer: Emotional Freedom Techniques / EFT Counselling & Therapy. Tap points, stress response, when it helps.',
      category: 'EFT / EFCT',
      platforms: ['Instagram', 'Blog', 'Newsletter'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W27',
      tags: ['explainer', 'education', 'basics'],
      links: [],
      notes: 'Carousel: 1) what it is 2) how tapping works 3) what it helps with 4) myth vs fact.',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(4, {
      title: 'What is EFW?',
      description:
        'Equine-Facilitated Wellness intro. What happens in a session, the horse as co-facilitator, who it is for.',
      category: 'EFW',
      platforms: ['Instagram', 'Blog'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W29',
      tags: ['explainer', 'horses', 'education'],
      links: [],
      notes: 'Need: photo consent / ranch location details before publishing.',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(5, {
      title: 'Substance use as trauma-informed coping',
      description:
        'Reframe substance use as adaptive coping. Reduce shame, invite curiosity. Sensitive, non-clinical language.',
      category: 'Substance Use',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['trauma-informed', 'shame-reduction', 'coping'],
      links: [],
      notes: 'Review wording with clinical lens before posting.',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(6, {
      title: 'Imposter syndrome in cis-passing / hetero-passing LGBTQ+ folks',
      description:
        'How passing privilege can complicate belonging and self-doubt. Nuanced, affirming.',
      category: 'Identity / LGBTQ+',
      platforms: ['Instagram', 'Blog'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['lgbtq+', 'identity', 'imposter-syndrome'],
      links: [],
      notes: '',
      contentPillar: 'Identity & belonging',
      platformReady: false,
    }),
    mk(7, {
      title: 'Gender & sexuality resource share',
      description:
        'Curated list of books, accounts, and supports for gender & sexuality exploration. Community-care post.',
      category: 'Identity / LGBTQ+',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'low',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['resources', 'community', 'lgbtq+'],
      links: [],
      notes: 'Collect 5-6 vetted resources first.',
      contentPillar: 'Community care',
      platformReady: false,
    }),
    mk(8, {
      title: 'Context in EFW',
      description:
        'How the ranch environment, the horse, and the relationship create safety. Therapeutic context piece.',
      category: 'EFW',
      platforms: ['Blog', 'Instagram'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['efw', 'safety', 'context'],
      links: [],
      notes: 'Waiting on ranch photo + a quote from the equine colleague.',
      contentPillar: 'Behind the work',
      platformReady: false,
    }),
    mk(9, {
      title: 'Safety first / therapeutic relationship',
      description:
        'Series opener on what makes this work safe: boundaries, consent, the therapeutic relationship.',
      category: 'Professional Education',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W30',
      tags: ['safety', 'boundaries', 'relationship'],
      links: [],
      notes: 'Part 1 of a 3-part "how we keep it safe" thread.',
      contentPillar: 'Credentials',
      platformReady: false,
    }),
    mk(10, {
      title: 'One step removed',
      description:
        'Neufeld concept: distance from the source of activation as a coping/attachment idea. Accessible framing.',
      category: 'Neurodivergence',
      platforms: ['Instagram'],
      priority: 'low',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['neufeld', 'attachment', 'concept'],
      links: [],
      notes: '',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(11, {
      title: 'Dependence and independence in childhood to adulthood',
      description:
        'Maturation-of-dependence framing (Neufeld): dependence is not the opposite of maturity.',
      category: 'Professional Education',
      platforms: ['Blog'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['neufeld', 'development', 'attachment'],
      links: [],
      notes: '',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(12, {
      title: 'Significance (Neufeld attachment theme)',
      description:
        'The need for significance and how it shows up in sessions and relationships.',
      category: 'Professional Education',
      platforms: ['Instagram'],
      priority: 'low',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['neufeld', 'attachment', 'significance'],
      links: [],
      notes: '',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(13, {
      title: 'Separation (Neufeld attachment theme)',
      description:
        'Separation sensitivity and its roots in attachment. Gentle, validating post.',
      category: 'Neurodivergence',
      platforms: ['Instagram'],
      priority: 'low',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['neufeld', 'attachment', 'separation'],
      links: [],
      notes: '',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(14, {
      title: 'Alpha complex (Neufeld)',
      description:
        'The alpha complex: when a child takes on the alpha role at home. Reframe for caregivers.',
      category: 'Professional Education',
      platforms: ['Blog', 'Newsletter'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['neufeld', 'caregiving', 'alpha-complex'],
      links: [],
      notes: '',
      contentPillar: 'Education',
      platformReady: false,
    }),
    mk(15, {
      title: 'Frustration / Neufeld’s traffic circle',
      description:
        'The "traffic circle" model of frustration and how it matures. A visual explainer would land well.',
      category: 'Neurodivergence',
      platforms: ['Instagram', 'YouTube'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W31',
      tags: ['neufeld', 'frustration', 'visual'],
      links: [],
      notes: 'Pair with a simple diagram of the traffic circle.',
      contentPillar: 'Education',
      platformReady: true,
    }),
    mk(16, {
      title: 'Supporting high-masking autistic / neurodivergent folks',
      description:
        'How masking works, the cost of it, and how this space can support unmasking safely.',
      category: 'Neurodivergence',
      platforms: ['Instagram', 'Blog', 'Newsletter'],
      priority: 'high',
      status: 'ideas',
      dueDate: '',
      targetWeek: '2026-W32',
      tags: ['neurodivergence', 'masking', 'support'],
      links: [],
      notes: 'Sensitivity read required — consider a guest voice.',
      contentPillar: 'Identity & belonging',
      platformReady: false,
    }),
    mk(17, {
      title: 'Groups / supports / workshops / book clubs',
      description:
        'Offer brainstorm: recurring peer group, a book club, a workshop series. Gauge interest first.',
      category: 'Group Offers',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'medium',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['group-offer', 'workshop', 'community'],
      links: [],
      notes: 'Possible pilot: "Nervous-system friendly book club".',
      contentPillar: 'Community care',
      platformReady: false,
    }),
    mk(18, {
      title: 'Personal reflection: why this work',
      description:
        'Occasional first-person note on what drew Loki to this work. Builds trust, keeps it human.',
      category: 'Personal Reflection',
      platforms: ['Instagram', 'Newsletter'],
      priority: 'low',
      status: 'ideas',
      dueDate: '',
      targetWeek: '',
      tags: ['reflection', 'origin', 'voice'],
      links: [],
      notes: 'Post sparingly — 1 every 4-6 weeks.',
      contentPillar: 'Behind the work',
      platformReady: false,
    }),
  ];
}
